"""pipeline trace and anomalies

Revision ID: bfa90b8739d0
Revises: 39522db15ff3
Create Date: 2026-08-08 15:52:30.011984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa90b8739d0'
down_revision: Union[str, None] = '39522db15ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_trace', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('anomalies', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('anomalies')
        batch_op.drop_column('pipeline_trace')

    # ### end Alembic commands ###
