"""webhook configs

Revision ID: 46ae0d9054f0
Revises: bfa90b8739d0
Create Date: 2026-08-11 12:34:45.938637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ae0d9054f0'
down_revision: Union[str, None] = 'bfa90b8739d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_configs_document_type'), ['document_type'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_configs_document_type'))

    op.drop_table('webhook_configs')
    # ### end Alembic commands ###
