SCHEMAS = {
 "invoice": {"name":"Invoice", "fields":[
  {"name":"vendor_name","label":"Vendor Name","type":"string","required":True}, {"name":"invoice_number","label":"Invoice Number","type":"string","required":True},
  {"name":"invoice_date","label":"Invoice Date","type":"date"}, {"name":"due_date","label":"Due Date","type":"date"}, {"name":"po_number","label":"PO Number","type":"string"},
  {"name":"gst_number","label":"GST Number","type":"string"}, {"name":"currency","label":"Currency","type":"string"}, {"name":"subtotal","label":"Subtotal","type":"number"},
  {"name":"tax","label":"Tax","type":"number"}, {"name":"total","label":"Total","type":"number","required":True}, {"name":"payment_terms","label":"Payment Terms","type":"string"}, {"name":"line_items","label":"Line Items","type":"array"}]},
 "purchase_order": {"name":"Purchase Order", "fields":[{"name":"supplier_name","label":"Supplier Name","type":"string","required":True},{"name":"po_number","label":"PO Number","type":"string","required":True},{"name":"order_date","label":"Order Date","type":"date"},{"name":"total_amount","label":"Total Amount","type":"number"},{"name":"line_items","label":"Line Items","type":"array"}]},
 "bill_of_lading": {"name":"Bill of Lading", "fields":[{"name":"bol_number","label":"BOL Number","type":"string","required":True},{"name":"shipper","label":"Shipper","type":"string"},{"name":"consignee","label":"Consignee","type":"string"},{"name":"vessel","label":"Vessel","type":"string"},{"name":"port_of_loading","label":"Port of Loading","type":"string"},{"name":"port_of_discharge","label":"Port of Discharge","type":"string"}]},
 "insurance_claim": {"name":"Insurance Claim", "fields":[{"name":"claim_number","label":"Claim Number","type":"string","required":True},{"name":"policy_number","label":"Policy Number","type":"string"},{"name":"claimant","label":"Claimant","type":"string"},{"name":"claim_amount","label":"Claim Amount","type":"number"},{"name":"incident_date","label":"Incident Date","type":"date"}]},
 "product_catalog": {"name":"Product Catalog", "fields":[{"name":"catalog_name","label":"Catalog Name","type":"string"},{"name":"supplier","label":"Supplier","type":"string"},{"name":"products","label":"Products","type":"array"}]},
 "customs_declaration": {"name":"Customs Declaration", "fields":[{"name":"declaration_number","label":"Declaration Number","type":"string","required":True},{"name":"importer","label":"Importer","type":"string"},{"name":"country_of_origin","label":"Country of Origin","type":"string"},{"name":"declared_value","label":"Declared Value","type":"number"}]},
 "medical_record": {"name":"Medical Record", "fields":[{"name":"patient_name","label":"Patient Name","type":"string","required":True},{"name":"record_number","label":"Record Number","type":"string"},{"name":"date_of_service","label":"Date of Service","type":"date"},{"name":"diagnosis","label":"Diagnosis","type":"string"}]}
}
